In [1]:
library(GLMsData); data(gestation); attach(gestation)

In [2]:
colnames(gestation)

[1] "Age"    "Births" "Weight" "SD"

In [3]:
head(gestation)

  Age Births Weight SD
1 22  1      0.520     NA
2 23  1      0.700     NA
3 25  1      1.000     NA
4 27  1      1.170     NA
5 28  6      1.198  0.121
6 29  1      1.480     NA

In [8]:
reg <- lm(Weight ~ Age)

In [9]:
summary(reg)

Call:
lm(formula = Weight ~ Age)

Residuals:
    Min      1Q  Median      3Q     Max
-0.4179 -0.1176  0.0628  0.1435  0.2640

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) -3.049879   0.232945  -13.09 5.87e-11 ***
Age          0.159483   0.006778   23.53 1.63e-15 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.1999 on 19 degrees of freedom
Multiple R-squared:  0.9668,	Adjusted R-squared:  0.9651
F-statistic: 553.7 on 1 and 19 DF,  p-value: 1.627e-15

In [12]:
mult_reg <- lm(Weight ~ Age:Births)

In [14]:
summary(mult_reg)

Call:
lm(formula = Weight ~ Age:Births)

Residuals:
    Min      1Q  Median      3Q     Max
-1.4692 -0.5101 -0.2942  0.5996  1.7481

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 1.986e+00  2.288e-01   8.684 4.85e-08 ***
Age:Births  1.237e-04  4.121e-05   3.003  0.00731 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.9037 on 19 degrees of freedom
Multiple R-squared:  0.3219,	Adjusted R-squared:  0.2862
F-statistic: 9.018 on 1 and 19 DF,  p-value: 0.007314

In [16]:
mult_reg <- lm(Weight ~ Age+Births)

In [17]:
summary(mult_reg)

Call:
lm(formula = Weight ~ Age + Births)

Residuals:
     Min       1Q   Median       3Q      Max
-0.28643 -0.08433 -0.00658  0.08640  0.31648

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept) -2.8201920  0.2198637 -12.827 1.71e-10 ***
Age          0.1506209  0.0067566  22.292 1.47e-14 ***
Births       0.0009648  0.0003605   2.676   0.0154 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.1737 on 18 degrees of freedom
Multiple R-squared:  0.9763,	Adjusted R-squared:  0.9736
F-statistic: 370.2 on 2 and 18 DF,  p-value: 2.388e-15

In [21]:
confint(mult_reg, level=0.95)

            2.5 %         97.5 %
(Intercept) -3.2821085214 -2.358275435
Age          0.1364258447  0.164815975
Births       0.0002074161  0.001722269

In [22]:
confint(mult_reg, level = 0.99)

            0.5 %         99.5 %
(Intercept) -3.453057e+00 -2.18732734
Age          1.311725e-01  0.17006935
Births      -7.289549e-05  0.00200258

In [23]:
new_reg <- lm(Weight ~ Age+SD)

In [24]:
summary(new_reg)

Call:
lm(formula = Weight ~ Age + SD)

Residuals:
     Min       1Q   Median       3Q      Max
-0.49157 -0.11503  0.08455  0.14243  0.25689

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept) -3.48504    0.49686  -7.014 1.41e-05 ***
Age          0.16788    0.01354  12.397 3.36e-08 ***
SD           0.36226    0.56265   0.644    0.532
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.2276 on 12 degrees of freedom
  (6 observations deleted due to missingness)
Multiple R-squared:  0.9319,	Adjusted R-squared:  0.9206
F-statistic: 82.13 on 2 and 12 DF,  p-value: 9.959e-08

In [25]:
confint(new_reg, level=0.95)

            2.5 %      97.5 %
(Intercept) -4.5676060 -2.4024640
Age          0.1383746  0.1973835
SD          -0.8636514  1.5881677

In [26]:
confint(new_reg, level=0.99)

            0.5 %     99.5 %
(Intercept) -5.002722 -1.9673480
Age          0.126516  0.2092422
SD          -1.356379  2.0808956

In [27]:
confint(new_reg, level=1)

            0 %  100 %
(Intercept) -Inf Inf
Age         -Inf Inf
SD          -Inf Inf